### ISSUE TITLE
Max 500 workers by page

### ISSUE THREAD

**Issue by Leonigas** [Elompenta/antpool-php-api#18]
Hi,

I figure out a restriction with the antpool API : we can get only 500 workers per page. After 500, we need to specify a number of page to get the others worker.

In the option on you get method, it is not possible to change the parameter "page" as it should be. Do you want me to add this feature ?

Regards
Léo

**Comment by AysadKozanoglu** [comment]
> Hi,
> 
> I figure out a restriction with the antpool API : we can get only 500 workers per page. After 500, we need to specify a number of page to get the others worker.
> 
> In the option on you get method, it is not possible to change the parameter "page" as it should be. Do you want me to add this feature ?
> 
> Regards
> Léo

Four your mind: 
AntPool's application programming interface (API) Request limits

Do not make more than 600 request per 10 minutes or we will ban your IP address.

**Comment by Leonigas** [comment]
Yes, I do 1 request to get 500 workers, and 1 request to get the others (page 2). That make 2 requests, not 500 ....

**Comment by AysadKozanoglu** [comment]
> Yes, I do 1 request to get 500 workers, and 1 request to get the others (page 2). That make 2 requests, not 500 ....

Ok anyway. I forked antpool-php-api and expanded the code for multi Accounts api calls with json pretty output.

I maked pull requestor new code 

Kindly check 
https://github.com/AysadKozanoglu/antpool-php-api

**Comment by Elompenta** [comment]
closed - please check my post: https://github.com/Elompenta/antpool-php-api/commit/7ae015d0d2c5bfe71b6b0eb224073d5dd5175a22
