### ISSUE TITLE
Help on showing isolated information

### ISSUE THREAD

**Issue by natanvferreira** [Elompenta/antpool-php-api#21]
Hello, I'm new to programming and I would like to know how I do to show the data that are inside custom.php without without an array, example
When I give print_r ($ ant-> get ('poolStats')); he returns me a lot of information I wanted to get just one of the information he shows me

**Comment by Elompenta** [comment]
Hi @natanvferreira,

I think this is a good link for you to checkup the basics.
https://www.php.net/manual/de/sdo.sample.getset.php

I close this issue ;)
