### ISSUE TITLE
Error when request

### ISSUE THREAD

**Issue by balydeg** [Elompenta/antpool-php-api#22]
Hi, i have Signature error message when request, have solution:

`API Error: stdClass Object
(
    [code] => -7
    [message] => Signature error
)`

**Comment by Elompenta** [comment]
Like written in the main view:

Repo is no longer maintained
This software is no longer maintained. You are welcome to have a look at the current Forks. There you will find nice colleagues who develop this software further. https://github.com/Elompenta/antpool-php-api/network/members

I will no longer develop for this solution. So feel free to fix the code and provide a pull request or create a fork
