### ISSUE TITLE
Getting signature error

### ISSUE THREAD

**Issue by vgagnoncoll** [Elompenta/antpool-php-api#8]
Hello,

after registering a new api key and followed your instructions, I'm getting:
API Error: stdClass Object
(
    [code] => -7
    [message] => Signature error
)

**Comment by Elompenta** [comment]
Hi @vgagnoncoll 

the class is okay - my test setup works fine.
You have used your Username and not your email address in config file? 
(I've updated the documentation, that username is needed - not email)

**Comment by vgagnoncoll** [comment]
@Elompenta 
Thank you !
